turtlebot3: #namespace

    n_actions: 3 # We have 3 actions, Forwards,TurnLeft,TurnRight

    linear_forward_speed: 0.1 # Speed for going forwards
    linear_turn_speed: 0.00 # Lienar speed when turning
    angular_speed: 1.5 # Angular speed when turning Left or Right
    init_linear_forward_speed: 0.0 # Initial linear speed in which we start each episode
    init_linear_turn_speed: 0.0 # Initial angular speed in shich we start each episode
    
    new_ranges: 5 # How many laser readings we jump in each observation reading, the bigger the less laser resolution
    min_range: 0.1 # Minimum meters below wich we consider we have crashed
    max_laser_value: 6 # Value considered Ok, no wall
    min_laser_value: 0 # Value considered there is an obstacle or crashed

    # My rewards
    no_crash_reward_points: 0.5 # Reward for not crashing. Negative reward so they are incentivized to explore.
    crash_reward_points: 10000 # Reward for crashing (ending an episode)
    exploration_multi_factor: 100 # Number by which we multiply the increase in area explored (difference between the previous image similiarity and the current one)
    


    

